# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('basic', 'Basic'),
                    ('standard', 'Standard'),
                    ('premium', 'Premium'),
                ],
                default='',
                max_length=10,
            ),
        ),
    ]
